# Generated by Django 3.2.14 on 2022-07-22 03:27

import datetime
from django.db import migrations, models
import django.db.models.deletion
import videos.models


class Migration(migrations.Migration):

    dependencies = [
        ('videos', '0002_videoinvertedindex'),
    ]

    operations = [
        migrations.CreateModel(
            name='Channel',
            fields=[
                ('id', models.CharField(max_length=255, primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=1024)),
                ('profile_url', models.CharField(max_length=1024)),
                ('thumbnail', models.CharField(blank=True, max_length=1024)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
        ),
        migrations.RemoveField(
            model_name='video',
            name='youtube_link',
        ),
        migrations.AddField(
            model_name='video',
            name='is_outstanding',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='video',
            name='length_seconds',
            field=models.PositiveIntegerField(default=1),
        ),
        migrations.AddField(
            model_name='video',
            name='publish_date',
            field=models.DateField(default=datetime.date.today),
        ),
        migrations.AddField(
            model_name='video',
            name='subtitle',
            field=models.JSONField(null=True, validators=[videos.models.validate_subtitle]),
        ),
        migrations.AddField(
            model_name='video',
            name='thumbnails',
            field=models.JSONField(null=True, validators=[videos.models.validate_thumbnails]),
        ),
        migrations.AlterField(
            model_name='category',
            name='id',
            field=models.BigAutoField(primary_key=True, serialize=False),
        ),
        migrations.AlterField(
            model_name='video',
            name='id',
            field=models.CharField(max_length=255, primary_key=True, serialize=False),
        ),
        migrations.AlterField(
            model_name='video',
            name='title',
            field=models.CharField(max_length=1024),
        ),
        migrations.AddField(
            model_name='video',
            name='channel',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='videos.channel'),
        ),
    ]
