# Generated by Django 3.2.14 on 2022-07-25 03:32

import django.contrib.postgres.fields
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('videos', '0004_auto_20220722_0328'),
    ]

    operations = [
        migrations.CreateModel(
            name='TitleInvertedIndex',
            fields=[
                ('keyword', models.CharField(max_length=255, primary_key=True, serialize=False)),
                ('videosTitle', django.contrib.postgres.fields.ArrayField(base_field=models.CharField(max_length=255), blank=True, size=None)),
                ('videosId', django.contrib.postgres.fields.ArrayField(base_field=models.CharField(max_length=255), blank=True, size=None)),
            ],
        ),
    ]
